#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.24.1
#  in conjunction with Tcl version 8.6
#    Jul 26, 2019 02:22:45 PM CDT  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import Pred_S


def vp_start_gui(list_of_grades):
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1(root, list_of_grades)
    Pred_S.init(root, top)
    root.mainloop()


w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    Pred_S.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None, list_of_grades=None):
        self.list_of_grades = list_of_grades
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        font11 = "-family {Segoe UI} -size 13 -weight normal -slant "  \
            "roman -underline 0 -overstrike 0"
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("1170x684+221+72")
        top.title("New Toplevel")
        top.configure(background="#ffffff")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.Button1 = tk.Button(top)
        self.Button1.place(relx=0.846, rely=0.848, height=50, width=90)
        self.Button1.configure(activebackground="#ececec")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font=font11)
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''<< Back''')
        self.Button1.configure(width=10)

        self.BM_lbl = tk.Label(top)
        self.BM_lbl.place(relx=0.436, rely=0.409, height=21, width=34)
        self.BM_lbl.configure(activebackground="#f9f9f9")
        self.BM_lbl.configure(activeforeground="black")
        self.BM_lbl.configure(background="#d9d9d9")
        self.BM_lbl.configure(disabledforeground="#a3a3a3")
        self.BM_lbl.configure(foreground="#000000")
        self.BM_lbl.configure(highlightbackground="#d9d9d9")
        self.BM_lbl.configure(highlightcolor="black")
        self.BM_lbl.configure(text='''B-''')

        self.CP_lbl = tk.Label(top)
        self.CP_lbl.place(relx=0.47, rely=0.409, height=21, width=34)
        self.CP_lbl.configure(activebackground="#f9f9f9")
        self.CP_lbl.configure(activeforeground="black")
        self.CP_lbl.configure(background="#d9d9d9")
        self.CP_lbl.configure(disabledforeground="#a3a3a3")
        self.CP_lbl.configure(foreground="#000000")
        self.CP_lbl.configure(highlightbackground="#d9d9d9")
        self.CP_lbl.configure(highlightcolor="black")
        self.CP_lbl.configure(text='''C+''')

        self.C_lbl = tk.Label(top)
        self.C_lbl.place(relx=0.504, rely=0.409, height=21, width=34)
        self.C_lbl.configure(activebackground="#f9f9f9")
        self.C_lbl.configure(activeforeground="black")
        self.C_lbl.configure(background="#d9d9d9")
        self.C_lbl.configure(disabledforeground="#a3a3a3")
        self.C_lbl.configure(foreground="#000000")
        self.C_lbl.configure(highlightbackground="#d9d9d9")
        self.C_lbl.configure(highlightcolor="black")
        self.C_lbl.configure(text='''C''')

        self.DP_lbl = tk.Label(top)
        self.DP_lbl.place(relx=0.573, rely=0.409, height=21, width=34)
        self.DP_lbl.configure(activebackground="#f9f9f9")
        self.DP_lbl.configure(activeforeground="black")
        self.DP_lbl.configure(background="#d9d9d9")
        self.DP_lbl.configure(disabledforeground="#a3a3a3")
        self.DP_lbl.configure(foreground="#000000")
        self.DP_lbl.configure(highlightbackground="#d9d9d9")
        self.DP_lbl.configure(highlightcolor="black")
        self.DP_lbl.configure(text='''D+''')

        self.D_lbl = tk.Label(top)
        self.D_lbl.place(relx=0.607, rely=0.409, height=21, width=34)
        self.D_lbl.configure(activebackground="#f9f9f9")
        self.D_lbl.configure(activeforeground="black")
        self.D_lbl.configure(background="#d9d9d9")
        self.D_lbl.configure(disabledforeground="#a3a3a3")
        self.D_lbl.configure(foreground="#000000")
        self.D_lbl.configure(highlightbackground="#d9d9d9")
        self.D_lbl.configure(highlightcolor="black")
        self.D_lbl.configure(text='''D''')

        self.A_lbl = tk.Label(top)
        self.A_lbl.place(relx=0.299, rely=0.409, height=21, width=34)
        self.A_lbl.configure(activebackground="#f9f9f9")
        self.A_lbl.configure(activeforeground="black")
        self.A_lbl.configure(background="#d9d9d9")
        self.A_lbl.configure(disabledforeground="#a3a3a3")
        self.A_lbl.configure(foreground="#000000")
        self.A_lbl.configure(highlightbackground="#d9d9d9")
        self.A_lbl.configure(highlightcolor="black")
        self.A_lbl.configure(text='''A''')

        self.AM_lbl = tk.Label(top)
        self.AM_lbl.place(relx=0.333, rely=0.409, height=21, width=34)
        self.AM_lbl.configure(activebackground="#f9f9f9")
        self.AM_lbl.configure(activeforeground="black")
        self.AM_lbl.configure(background="#d9d9d9")
        self.AM_lbl.configure(disabledforeground="#a3a3a3")
        self.AM_lbl.configure(foreground="#000000")
        self.AM_lbl.configure(highlightbackground="#d9d9d9")
        self.AM_lbl.configure(highlightcolor="black")
        self.AM_lbl.configure(text='''A-''')

        self.BP_lbl = tk.Label(top)
        self.BP_lbl.place(relx=0.368, rely=0.409, height=21, width=34)
        self.BP_lbl.configure(activebackground="#f9f9f9")
        self.BP_lbl.configure(activeforeground="black")
        self.BP_lbl.configure(background="#d9d9d9")
        self.BP_lbl.configure(disabledforeground="#a3a3a3")
        self.BP_lbl.configure(foreground="#000000")
        self.BP_lbl.configure(highlightbackground="#d9d9d9")
        self.BP_lbl.configure(highlightcolor="black")
        self.BP_lbl.configure(text='''B+''')

        self.B_lbl = tk.Label(top)
        self.B_lbl.place(relx=0.402, rely=0.409, height=21, width=34)
        self.B_lbl.configure(activebackground="#f9f9f9")
        self.B_lbl.configure(activeforeground="black")
        self.B_lbl.configure(background="#d9d9d9")
        self.B_lbl.configure(disabledforeground="#a3a3a3")
        self.B_lbl.configure(foreground="#000000")
        self.B_lbl.configure(highlightbackground="#d9d9d9")
        self.B_lbl.configure(highlightcolor="black")
        self.B_lbl.configure(text='''B''')

        self.F_lbl = tk.Label(top)
        self.F_lbl.place(relx=0.641, rely=0.409, height=21, width=34)
        self.F_lbl.configure(activebackground="#f9f9f9")
        self.F_lbl.configure(activeforeground="black")
        self.F_lbl.configure(background="#d9d9d9")
        self.F_lbl.configure(disabledforeground="#a3a3a3")
        self.F_lbl.configure(foreground="#000000")
        self.F_lbl.configure(highlightbackground="#d9d9d9")
        self.F_lbl.configure(highlightcolor="black")
        self.F_lbl.configure(text='''F''')

        self.CM_lbl = tk.Label(top)
        self.CM_lbl.place(relx=0.538, rely=0.409, height=21, width=34)
        self.CM_lbl.configure(activebackground="#f9f9f9")
        self.CM_lbl.configure(activeforeground="black")
        self.CM_lbl.configure(background="#d9d9d9")
        self.CM_lbl.configure(disabledforeground="#a3a3a3")
        self.CM_lbl.configure(foreground="#000000")
        self.CM_lbl.configure(highlightbackground="#d9d9d9")
        self.CM_lbl.configure(highlightcolor="black")
        self.CM_lbl.configure(text='''C-''')

        self.AD_lbl = tk.Label(top)
        self.AD_lbl.place(relx=0.299, rely=0.468, height=21, width=34)
        self.AD_lbl.configure(activebackground="#f9f9f9")
        self.AD_lbl.configure(activeforeground="black")
        self.AD_lbl.configure(background="#d9d9d9")
        self.AD_lbl.configure(disabledforeground="#a3a3a3")
        self.AD_lbl.configure(foreground="#000000")
        self.AD_lbl.configure(highlightbackground="#d9d9d9")
        self.AD_lbl.configure(highlightcolor="black")
        self.AD_lbl.configure(text='''Label''')

        self.AMD_lbl = tk.Label(top)
        self.AMD_lbl.place(relx=0.333, rely=0.468, height=21, width=34)
        self.AMD_lbl.configure(activebackground="#f9f9f9")
        self.AMD_lbl.configure(activeforeground="black")
        self.AMD_lbl.configure(background="#d9d9d9")
        self.AMD_lbl.configure(disabledforeground="#a3a3a3")
        self.AMD_lbl.configure(foreground="#000000")
        self.AMD_lbl.configure(highlightbackground="#d9d9d9")
        self.AMD_lbl.configure(highlightcolor="black")
        self.AMD_lbl.configure(text='''Label''')

        self.BPD_lbl = tk.Label(top)
        self.BPD_lbl.place(relx=0.368, rely=0.468, height=21, width=34)
        self.BPD_lbl.configure(activebackground="#f9f9f9")
        self.BPD_lbl.configure(activeforeground="black")
        self.BPD_lbl.configure(background="#d9d9d9")
        self.BPD_lbl.configure(disabledforeground="#a3a3a3")
        self.BPD_lbl.configure(foreground="#000000")
        self.BPD_lbl.configure(highlightbackground="#d9d9d9")
        self.BPD_lbl.configure(highlightcolor="black")
        self.BPD_lbl.configure(text='''Label''')

        self.BD_lbl = tk.Label(top)
        self.BD_lbl.place(relx=0.402, rely=0.468, height=21, width=34)
        self.BD_lbl.configure(activebackground="#f9f9f9")
        self.BD_lbl.configure(activeforeground="black")
        self.BD_lbl.configure(background="#d9d9d9")
        self.BD_lbl.configure(disabledforeground="#a3a3a3")
        self.BD_lbl.configure(foreground="#000000")
        self.BD_lbl.configure(highlightbackground="#d9d9d9")
        self.BD_lbl.configure(highlightcolor="black")
        self.BD_lbl.configure(text='''Label''')

        self.BMD_lbl = tk.Label(top)
        self.BMD_lbl.place(relx=0.436, rely=0.468, height=21, width=34)
        self.BMD_lbl.configure(activebackground="#f9f9f9")
        self.BMD_lbl.configure(activeforeground="black")
        self.BMD_lbl.configure(background="#d9d9d9")
        self.BMD_lbl.configure(disabledforeground="#a3a3a3")
        self.BMD_lbl.configure(foreground="#000000")
        self.BMD_lbl.configure(highlightbackground="#d9d9d9")
        self.BMD_lbl.configure(highlightcolor="black")
        self.BMD_lbl.configure(text='''Label''')

        self.CPD_lbl = tk.Label(top)
        self.CPD_lbl.place(relx=0.47, rely=0.468, height=21, width=34)
        self.CPD_lbl.configure(activebackground="#f9f9f9")
        self.CPD_lbl.configure(activeforeground="black")
        self.CPD_lbl.configure(background="#d9d9d9")
        self.CPD_lbl.configure(disabledforeground="#a3a3a3")
        self.CPD_lbl.configure(foreground="#000000")
        self.CPD_lbl.configure(highlightbackground="#d9d9d9")
        self.CPD_lbl.configure(highlightcolor="black")
        self.CPD_lbl.configure(text='''Label''')

        self.CD_lbl = tk.Label(top)
        self.CD_lbl.place(relx=0.504, rely=0.468, height=21, width=34)
        self.CD_lbl.configure(activebackground="#f9f9f9")
        self.CD_lbl.configure(activeforeground="black")
        self.CD_lbl.configure(background="#d9d9d9")
        self.CD_lbl.configure(disabledforeground="#a3a3a3")
        self.CD_lbl.configure(foreground="#000000")
        self.CD_lbl.configure(highlightbackground="#d9d9d9")
        self.CD_lbl.configure(highlightcolor="black")
        self.CD_lbl.configure(text='''Label''')

        self.CMD_lbl = tk.Label(top)
        self.CMD_lbl.place(relx=0.538, rely=0.468, height=21, width=34)
        self.CMD_lbl.configure(activebackground="#f9f9f9")
        self.CMD_lbl.configure(activeforeground="black")
        self.CMD_lbl.configure(background="#d9d9d9")
        self.CMD_lbl.configure(disabledforeground="#a3a3a3")
        self.CMD_lbl.configure(foreground="#000000")
        self.CMD_lbl.configure(highlightbackground="#d9d9d9")
        self.CMD_lbl.configure(highlightcolor="black")
        self.CMD_lbl.configure(text='''Label''')

        self.DPD_lbl = tk.Label(top)
        self.DPD_lbl.place(relx=0.573, rely=0.468, height=21, width=34)
        self.DPD_lbl.configure(activebackground="#f9f9f9")
        self.DPD_lbl.configure(activeforeground="black")
        self.DPD_lbl.configure(background="#d9d9d9")
        self.DPD_lbl.configure(disabledforeground="#a3a3a3")
        self.DPD_lbl.configure(foreground="#000000")
        self.DPD_lbl.configure(highlightbackground="#d9d9d9")
        self.DPD_lbl.configure(highlightcolor="black")
        self.DPD_lbl.configure(text='''Label''')

        self.course_name_lbl = tk.Label(top)
        self.course_name_lbl.place(relx=0.333, rely=0.322, height=21, width=354)
        self.course_name_lbl.configure(activebackground="#f9f9f9")
        self.course_name_lbl.configure(activeforeground="black")
        self.course_name_lbl.configure(background="#d9d9d9")
        self.course_name_lbl.configure(disabledforeground="#a3a3a3")
        self.course_name_lbl.configure(foreground="#000000")
        self.course_name_lbl.configure(highlightbackground="#d9d9d9")
        self.course_name_lbl.configure(highlightcolor="black")
        self.course_name_lbl.configure(text='''Course''')

        self.DD_lbl = tk.Label(top)
        self.DD_lbl.place(relx=0.607, rely=0.468, height=21, width=34)
        self.DD_lbl.configure(activebackground="#f9f9f9")
        self.DD_lbl.configure(activeforeground="black")
        self.DD_lbl.configure(background="#d9d9d9")
        self.DD_lbl.configure(disabledforeground="#a3a3a3")
        self.DD_lbl.configure(foreground="#000000")
        self.DD_lbl.configure(highlightbackground="#d9d9d9")
        self.DD_lbl.configure(highlightcolor="black")
        self.DD_lbl.configure(text='''Label''')

        self.FD_lbl = tk.Label(top)
        self.FD_lbl.place(relx=0.641, rely=0.468, height=21, width=34)
        self.FD_lbl.configure(activebackground="#f9f9f9")
        self.FD_lbl.configure(activeforeground="black")
        self.FD_lbl.configure(background="#d9d9d9")
        self.FD_lbl.configure(disabledforeground="#a3a3a3")
        self.FD_lbl.configure(foreground="#000000")
        self.FD_lbl.configure(highlightbackground="#d9d9d9")
        self.FD_lbl.configure(highlightcolor="black")
        self.FD_lbl.configure(text='''Label''')

        self.TSeparator1 = ttk.Separator(top)
        self.TSeparator1.place(relx=-0.137, rely=0.351, relheight=0.292)
        self.TSeparator1.configure(orient="vertical")

        self.show_probability(self.list_of_grades)

    def show_probability(self, list_of_grades):
        if list_of_grades is None:
            return
        count = 0
        self.course_name_lbl.configure(text=list_of_grades[count])
        count = + 1
        self.AD_lbl.configure(text=list_of_grades[count])
        count = + 1
        self.AMD_lbl.configure(text=list_of_grades[count])
        count = + 1
        self.BPD_lbl.configure(text=list_of_grades[count])
        count = + 1
        self.BD_lbl.configure(text=list_of_grades[count])
        count = + 1
        self.BMD_lbl.configure(text=list_of_grades[count])
        count = + 1
        self.CPD_lbl.configure(text=list_of_grades[count])
        count = + 1
        self.CD_lbl.configure(text=list_of_grades[count])
        count = + 1
        self.CMD_lbl.configure(text=list_of_grades[count])
        count = + 1
        self.DPD_lbl.configure(text=list_of_grades[count])
        count = + 1
        self.DD_lbl.configure(text=list_of_grades[count])
        count = + 1
        self.FD_lbl.configure(text=list_of_grades[count])
        return

if __name__ == '__main__':
    vp_start_gui()





