#############################################################################
# Generated by PAGE version 4.24.1
#  in conjunction with Tcl version 8.6
#  Jul 26, 2019 02:22:43 PM CDT  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}

# vTcl Code to Load User Fonts

vTcl:font:add_font \
    "-family {Segoe UI} -size 13 -weight normal -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font11


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top42
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top42
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}


proc vTclWindow.top42 {base} {
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 1170x684+221+72
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 3204 881
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    button $top.but55 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font11,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text {<< Back   } -width 10 
    vTcl:DefineAlias "$top.but55" "Button1" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab58 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text B- 
    vTcl:DefineAlias "$top.lab58" "B-_lbl" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.lab58
    label $top.lab59 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text C+ 
    vTcl:DefineAlias "$top.lab59" "C+_lbl" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.lab59
    label $top.lab60 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text C 
    vTcl:DefineAlias "$top.lab60" "C_lbl" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.lab60
    label $top.lab61 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text D+ \
        -underline -1 
    vTcl:DefineAlias "$top.lab61" "D+_lbl" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.lab61
    label $top.lab62 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text D 
    vTcl:DefineAlias "$top.lab62" "D_lbl" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.lab62
    label $top.lab63 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text A 
    vTcl:DefineAlias "$top.lab63" "A_lbl" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.lab63
    label $top.lab64 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text A- 
    vTcl:DefineAlias "$top.lab64" "A-_lbl" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.lab64
    label $top.lab65 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text B+ 
    vTcl:DefineAlias "$top.lab65" "B+_lbl" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.lab65
    label $top.lab66 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text B 
    vTcl:DefineAlias "$top.lab66" "B_lbl" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.lab66
    label $top.lab67 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text F 
    vTcl:DefineAlias "$top.lab67" "F_lbl" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.lab67
    label $top.lab68 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text C- 
    vTcl:DefineAlias "$top.lab68" "C-_lbl" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.lab68
    label $top.lab69 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Label 
    vTcl:DefineAlias "$top.lab69" "AD_lbl" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.lab69
    label $top.lab70 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Label 
    vTcl:DefineAlias "$top.lab70" "A-D_lbl" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.lab70
    label $top.lab71 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Label 
    vTcl:DefineAlias "$top.lab71" "B+D_lbl" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.lab71
    label $top.lab72 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Label 
    vTcl:DefineAlias "$top.lab72" "BD_lbl" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.lab72
    label $top.lab73 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Label 
    vTcl:DefineAlias "$top.lab73" "B-D_lbl" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.lab73
    label $top.lab74 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Label 
    vTcl:DefineAlias "$top.lab74" "C+D_lbl" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.lab74
    label $top.lab75 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Label 
    vTcl:DefineAlias "$top.lab75" "CD_lbl" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.lab75
    label $top.lab76 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Label 
    vTcl:DefineAlias "$top.lab76" "C-D_lbl" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.lab76
    label $top.lab77 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Label 
    vTcl:DefineAlias "$top.lab77" "D+D_lbl" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.lab77
    label $top.lab79 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Course 
    vTcl:DefineAlias "$top.lab79" "course_name_lbl" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.lab79
    label $top.lab83 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Label 
    vTcl:DefineAlias "$top.lab83" "DD_lbl" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.lab83
    label $top.lab84 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Label 
    vTcl:DefineAlias "$top.lab84" "FD_lbl" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.lab84
    ttk::separator $top.tSe43 \
        -orient vertical 
    vTcl:DefineAlias "$top.tSe43" "TSeparator1" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.but55 \
        -in $top -x 990 -y 580 -width 90 -relwidth 0 -height 50 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab58 \
        -in $top -x 510 -y 0 -rely 0.409 -width 34 -relwidth 0 -anchor nw \
        -bordermode ignore 
    place $top.lab59 \
        -in $top -x 550 -y 280 -width 34 -relwidth 0 -anchor nw \
        -bordermode ignore 
    place $top.lab60 \
        -in $top -x 590 -y 280 -width 34 -relwidth 0 -anchor nw \
        -bordermode ignore 
    place $top.lab61 \
        -in $top -x 670 -y 280 -width 34 -relwidth 0 -anchor nw \
        -bordermode ignore 
    place $top.lab62 \
        -in $top -x 710 -y 280 -width 34 -relwidth 0 -anchor nw \
        -bordermode ignore 
    place $top.lab63 \
        -in $top -x 350 -y 280 -width 0 -relwidth 0.029 -anchor nw \
        -bordermode ignore 
    place $top.lab64 \
        -in $top -x 390 -y 280 -width 34 -relwidth 0 -anchor nw \
        -bordermode ignore 
    place $top.lab65 \
        -in $top -x 430 -y 0 -rely 0.409 -width 34 -relwidth 0 -anchor nw \
        -bordermode ignore 
    place $top.lab66 \
        -in $top -x 470 -y 280 -width 34 -relwidth 0 -anchor nw \
        -bordermode ignore 
    place $top.lab67 \
        -in $top -x 750 -y 280 -width 34 -relwidth 0 -anchor nw \
        -bordermode ignore 
    place $top.lab68 \
        -in $top -x 630 -y 280 -width 34 -relwidth 0 -anchor nw \
        -bordermode ignore 
    place $top.lab69 \
        -in $top -x 350 -y 320 -width 34 -relwidth 0 -anchor nw \
        -bordermode ignore 
    place $top.lab70 \
        -in $top -x 390 -y 320 -width 34 -relwidth 0 -anchor nw \
        -bordermode ignore 
    place $top.lab71 \
        -in $top -x 430 -y 320 -width 34 -relwidth 0 -anchor nw \
        -bordermode ignore 
    place $top.lab72 \
        -in $top -x 470 -y 320 -width 34 -relwidth 0 -anchor nw \
        -bordermode ignore 
    place $top.lab73 \
        -in $top -x 510 -y 320 -width 34 -relwidth 0 -anchor nw \
        -bordermode ignore 
    place $top.lab74 \
        -in $top -x 550 -y 320 -width 34 -relwidth 0 -anchor nw \
        -bordermode ignore 
    place $top.lab75 \
        -in $top -x 590 -y 320 -width 34 -relwidth 0 -anchor nw \
        -bordermode ignore 
    place $top.lab76 \
        -in $top -x 630 -y 320 -width 34 -relwidth 0 -anchor nw \
        -bordermode ignore 
    place $top.lab77 \
        -in $top -x 670 -y 320 -width 34 -relwidth 0 -anchor nw \
        -bordermode ignore 
    place $top.lab79 \
        -in $top -x 390 -y 220 -width 354 -relwidth 0 -height 21 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab83 \
        -in $top -x 710 -y 320 -width 34 -relwidth 0 -anchor nw \
        -bordermode ignore 
    place $top.lab84 \
        -in $top -x 750 -y 320 -width 34 -relwidth 0 -anchor nw \
        -bordermode ignore 
    place $top.tSe43 \
        -in $top -x -160 -y 240 -height 200 -anchor nw -bordermode inside 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

