#############################################################################
# Generated by PAGE version 4.24.1
#  in conjunction with Tcl version 8.6
#  Jul 31, 2019 01:14:11 PM CDT  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}

# vTcl Code to Load User Fonts

vTcl:font:add_font \
    "-family {Segoe UI} -size 9 -weight normal -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font9


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top42
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top42
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}


proc vTclWindow.top42 {base} {
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m48" -background {#d9d9d9} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 1123x728+331+78
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 3204 881
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    button $top.but43 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font9,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text Predict 
    vTcl:DefineAlias "$top.but43" "predict_btn" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.m48
    menu $site_3_0 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -font TkMenuFont -foreground {#000000} \
        -tearoff 0 
    vTcl::widgets::ttk::scrolledlistbox::CreateCmd $top.scr58 \
        -background {#d9d9d9} -height 605 -highlightbackground {#d9d9d9} \
        -highlightcolor black -width 341 
    vTcl:DefineAlias "$top.scr58" "course_list_slb" vTcl:WidgetProc "Toplevel1" 1

    $top.scr58.01 configure -background white \
        -disabledforeground #a3a3a3 \
        -font TkFixedFont \
        -foreground black \
        -height 3 \
        -highlightbackground #d9d9d9 \
        -highlightcolor #d9d9d9 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -width 10
    ttk::label $top.tLa60 \
        -background {#d9d9d9} -foreground {#000000} -font TkDefaultFont \
        -relief flat -text {Course List} 
    vTcl:DefineAlias "$top.tLa60" "course_list_lbl" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $top.tLa61 \
        -background {#d9d9d9} -foreground {#000000} \
        -font $::vTcl(fonts,vTcl:font9,object) -relief flat \
        -text {Prerequisite Classes} 
    vTcl:DefineAlias "$top.tLa61" "prereq_lbl" vTcl:WidgetProc "Toplevel1" 1
    button $top.but71 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font9,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text Enter 
    vTcl:DefineAlias "$top.but71" "enter_btn" vTcl:WidgetProc "Toplevel1" 1
    button $top.but72 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font9,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text Remove 
    vTcl:DefineAlias "$top.but72" "remove_btn" vTcl:WidgetProc "Toplevel1" 1
    vTcl::widgets::ttk::scrolledlistbox::CreateCmd $top.scr50 \
        -background {#d9d9d9} -height 75 -highlightbackground {#d9d9d9} \
        -highlightcolor black -width 125 
    vTcl:DefineAlias "$top.scr50" "prereq_slb" vTcl:WidgetProc "Toplevel1" 1

    $top.scr50.01 configure -background white \
        -disabledforeground #a3a3a3 \
        -font TkFixedFont \
        -foreground black \
        -height 3 \
        -highlightbackground #d9d9d9 \
        -highlightcolor #d9d9d9 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -width 10
    entry $top.ent44 \
        -background white -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font9,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black 
    vTcl:DefineAlias "$top.ent44" "termgpa_ety" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent45 \
        -background white -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font9,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black 
    vTcl:DefineAlias "$top.ent45" "cumulativegpa_ety" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab47 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font9,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {First Prereq Cumulative GPA} 
    vTcl:DefineAlias "$top.lab47" "cumulativegpa_lbl" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab49 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font9,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {First Prereq Term GPA} 
    vTcl:DefineAlias "$top.lab49" "termgpa_lbl" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab51 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font9,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Struggled Up Until First Prereq} 
    vTcl:DefineAlias "$top.lab51" "struggled_lbl" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $top.tCo56 \
        -font $::vTcl(fonts,vTcl:font9,object) -textvariable combobox \
        -foreground {} -background {} -takefocus {} 
    vTcl:DefineAlias "$top.tCo56" "struggled_cbb" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $top.rad80 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font9,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -justify left \
        -text Root -variable {} 
    vTcl:DefineAlias "$top.rad80" "root_rbtn" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $top.rad81 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font9,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -justify left \
        -text All -variable {} 
    vTcl:DefineAlias "$top.rad81" "all_rbtn" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $top.rad82 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font9,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -justify left \
        -text Immediate -variable {} 
    vTcl:DefineAlias "$top.rad82" "imme_rbtn" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $top.tLa43 \
        -background {#d9d9d9} -foreground {#000000} \
        -font $::vTcl(fonts,vTcl:font9,object) -relief flat \
        -text {Model Type} 
    vTcl:DefineAlias "$top.tLa43" "model_type_lbl" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $top.tCo44 \
        -font TkTextFont -textvariable combobox -foreground {} -background {} \
        -takefocus {} 
    vTcl:DefineAlias "$top.tCo44" "grade_ety" vTcl:WidgetProc "Toplevel1" 1
    vTcl::widgets::ttk::scrolledlistbox::CreateCmd $top.scr46 \
        -background {#d9d9d9} -height 345 -highlightbackground {#d9d9d9} \
        -highlightcolor black -width 101 
    vTcl:DefineAlias "$top.scr46" "prereq_grades_listbox" vTcl:WidgetProc "Toplevel1" 1

    $top.scr46.01 configure -background white \
        -disabledforeground #a3a3a3 \
        -font TkFixedFont \
        -foreground black \
        -height 3 \
        -highlightbackground #d9d9d9 \
        -highlightcolor #d9d9d9 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -takefocus 0 \
        -width 10
    ttk::label $top.tLa47 \
        -background {#d9d9d9} -foreground {#000000} \
        -font $::vTcl(fonts,vTcl:font9,object) -relief flat -text Grades 
    vTcl:DefineAlias "$top.tLa47" "prereq_grades_lbl" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $top.tLa48 \
        -background {#d9d9d9} -foreground {#000000} \
        -font $::vTcl(fonts,vTcl:font9,object) -relief flat -takefocus 0 \
        -text {Prerequisite Grade} 
    vTcl:DefineAlias "$top.tLa48" "prereq_grade_entry_lbl" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.but43 \
        -in $top -x 700 -y 650 -anchor nw -bordermode ignore 
    place $top.scr58 \
        -in $top -x 10 -y 110 -width 341 -relwidth 0 -height 605 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tLa60 \
        -in $top -x 130 -y 90 -anchor nw -bordermode ignore 
    place $top.tLa61 \
        -in $top -x 570 -y 70 -anchor nw -bordermode ignore 
    place $top.but71 \
        -in $top -x 490 -y 536 -width 38 -height 24 -anchor nw \
        -bordermode ignore 
    place $top.but72 \
        -in $top -x 560 -y 536 -width 54 -height 24 -anchor nw \
        -bordermode ignore 
    place $top.scr50 \
        -in $top -x 480 -y 100 -width 311 -relwidth 0 -height 345 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent44 \
        -in $top -x 830 -y 510 -width 144 -relwidth 0 -height 20 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent45 \
        -in $top -x 830 -y 480 -width 144 -relwidth 0 -height 20 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab47 \
        -in $top -x 650 -y 480 -width 173 -relwidth 0 -height 21 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab49 \
        -in $top -x 690 -y 510 -width 120 -relwidth 0 -height 21 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab51 \
        -in $top -x 650 -y 540 -anchor nw -bordermode ignore 
    place $top.tCo56 \
        -in $top -x 830 -y 540 -anchor nw -bordermode ignore 
    place $top.rad80 \
        -in $top -x 20 -y 50 -anchor nw -bordermode ignore 
    place $top.rad81 \
        -in $top -x 140 -y 50 -anchor nw -bordermode ignore 
    place $top.rad82 \
        -in $top -x 230 -y 50 -anchor nw -bordermode ignore 
    place $top.tLa43 \
        -in $top -x 130 -y 20 -width 67 -relwidth 0 -height 19 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tCo44 \
        -in $top -x 510 -y 507 -width 83 -relwidth 0 -height 21 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.scr46 \
        -in $top -x 790 -y 100 -width 101 -relwidth 0 -height 345 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $top.tLa47 \
        -in $top -x 810 -y 70 -width 47 -relwidth 0 -height 19 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tLa48 \
        -in $top -x 500 -y 480 -width 107 -relwidth 0 -height 19 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

